#Configuation for robot odometry EKF
#
frequency: 50

odom0: /zed_node/odom
odom0_config: [true, true, true,     # Use XYZ position
               true, true, true,     # Use RPY orientation
               false, false, false,  # No positional velocity
               false, false, false,  # No rotational velocity
               false, false, false,  # No acceleration
               false, false, false]
odom0_differential: false

#odom1: /jackal_velocity_controller/odom
#odom1_config: [false, false, false,
#               false, false, false,
#               true, true, true,
#               true, true, true,
#               false, false, false]

imu0: /zed_node/imu/data
imu0_config: [false, false, false,  # No XYZ position
              true, true, true,     # Use RPY orientation
              false, false, false,  # No positional velocity
              true, true, true,     # Use rotational velocity
              true, true, true,     # Use linear acceleration
              false, false, false]  # No rotational acceleration
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true
two_d_mode: true
