#Configuation for robot odometry EKF
#
frequency: 50

odom0: /zed_node/odom
odom0_config: [true, true, true,
               true, true, true,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false

odom1: /jackal_velocity_controller/odom
odom1_config: [false, false, false,
               false, false, false,
               true, true, true,
               true, true, true,
               false, false, false]

imu0: /zed_node/imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true
two_d_mode: true
